---
title: "Tecnologias, herramientas y lenguajes de programacion 1960-2023"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}

library(flexdashboard)
library(readxl)
library(tidyverse)
library(plotly)

Data <- read_excel("Data.xlsx")

# Calculo del numero de muestra

n <- ((1.96**2) * ((1336/3989) * (1 - (1336/3989)))) / 0.02**2
n <- round(n)
# Tamaño de meustra para proporciones


set.seed(00065280) # Establecer una semilla para reproducibilidad
tamano_muestra <- n # Reemplaza 'n' con el tamaño deseado de la muestra
Muestra <- Data[sample(nrow(Data), tamano_muestra), ]


# Muestreo aleatorio
library(zoo)

# Reemplazar NA por la mediana en variables numéricas
Muestra$appeared <- na.aggregate(Muestra$appeared, FUN = median)
Muestra$lastActivity <- na.aggregate(Muestra$lastActivity, FUN = median)
Muestra$numberOfUsers <- na.aggregate(Muestra$numberOfUsers, FUN = median)

# Reemplazar NA por la moda en variables categóricas
Mode <- function(x) {
  uniq_x <- unique(x)
  uniq_x[which.max(tabulate(match(x, uniq_x)))]
}
Muestra$type <- na.aggregate(Muestra$type, FUN = function(x) Mode(x)[1])
Muestra$website <- na.aggregate(Muestra$website, FUN = function(x) Mode(x)[1])
Muestra$country <- na.aggregate(Muestra$country, FUN = function(x) Mode(x)[1])

```

APPEARED 
==============


Rows {data-width=650, .tabset}
-----------------------------------------------------------------------
### Histogram
```{r}
p = ggplot(data = Muestra, aes(x = appeared)) + geom_histogram(bins = 20)
fig = ggplotly(p)
fig
```


### Chart B

```{r}

```


### Chart B

```{r}

```
Rows {data-width=650}
---------------
### Chart x

```{r}

```

 
### Chart y

```{r}

```
